sortOptions:
  order: fifo
configMapGenerator:
  - name: snmp-exporter-configmap
    namespace: prometheus
    files:
      - snmp.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - all.yaml
